### ISSUE TITLE
Unintended error when running `npm i` in a locally stored repository

### ISSUE THREAD

**Issue by asamuzaK** [cdoublev/css#7]
It is because `prepare` runs on local npm install.
Ref: [scripts | npm Docs](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts)

log:
``` console
>npm i

> @cdoublev/css@0.1.0 prepare
> npm run build:interface && npm run build:definitions

> @cdoublev/css@0.1.0 build:interface
> node ./scripts/interface.js

> @cdoublev/css@0.1.0 build:definitions
> npm run build:definitions:extract && npm run build:definitions:initial

> @cdoublev/css@0.1.0 build:definitions:extract
> node ./scripts/extract.js

> @cdoublev/css@0.1.0 build:definitions:initial
> node ./scripts/initial.js

Parse error: cannot parse initial value of "rendering-intent"
C:\Users\XXX\Documents\GitHub\css\lib\utils\string.js:7
    return value.includes("'") ? `"${value}"` : `'${value}'`
                 ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at addQuotes (C:\Users\XXX\Documents\GitHub\css\lib\utils\string.js:7:18)
    at C:\Users\XXX\Documents\GitHub\css\scripts\initial.js:142:55
    at Array.forEach (<anonymous>)
    at C:\Users\XXX\Documents\GitHub\css\scripts\initial.js:136:41
    at Array.reduce (<anonymous>)
    at serializeDescriptorDefinitions (C:\Users\XXX\Documents\GitHub\css\scripts\initial.js:133:40)
    at serializeDefinitions (C:\Users\XXX\Documents\GitHub\css\scripts\initial.js:165:25)
    at Object.<anonymous> (C:\Users\XXX\Documents\GitHub\css\scripts\initial.js:172:1)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)

Node.js v22.12.0
npm error code 1
npm error path C:\Users\XXX\Documents\GitHub\css
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build:interface && npm run build:definitions
npm error A complete log of this run can be found in: C:\Users\XXX\AppData\Local\npm-cache\_logs\2024-12-18T02_36_45_225Z-debug-0.log
```

And these files were also overwritten.
* lib/descriptors/definitions.js
* lib/properties/definitions.js
* lib/values/definitions.js

Renaming `prepare` to something else, e.g. `prebuild`, should fix this issue.

Same happens when running `npm test` locally.
Maybe add something like `"test:local": "jest"`?

**Comment by cdoublev** [comment]
Thanks for bringing this to my attention. It should work now.

For (my personal) convenience, these definition files are currently versioned so the scripts generating them do not need to run when installing the package. You could have run the tests and use the entry points by restoring these definition files to the HEAD version.
